HPPMDotNetCore.MvcApp/Controllers/BlogController.cs
using HPPMDotNetCore.DbService;
using HPPMDotNetCore.Models;
using HPPMDotNetCore.Models.ApiModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Dynamic.Core;
using System.Linq.Expressions;
using System.Threading.Tasks;

namespace HPPMDotNetCore.MvcApp.Controllers
{
    public class BlogController : BaseController
    {
        private readonly EFDbContext _dbContext;

        public BlogController(EFDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        //https://localhost:3000/blog
        //https://localhost:3000/blog/index
        [ActionName("Index")]
        public IActionResult BlogIndex()
        {
            return View("BlogIndex");
        }

        [ActionName("List")]
        public async Task<IActionResult> BlogList(int pageNo = 1, int pageSize = 10)
        {
            var blogList = await _dbContext
               .Blogs
               .AsNoTracking()
               .OrderByDescending(x => x.Blog_Id)
               .ToPagination(pageNo, pageSize)
               .ToListAsync();

            //ResponseModel model = BaseResponseModel.GetSuccess(blogList);

            BlogListResponseModel model = new BlogListResponseModel();
            model.Resopnse = BaseResponseModel.GetSuccess();
            model.Blogs = blogList;
            return View("BlogList", model);
        }

        //Using Jquery Datatable
        [ActionName("blogTable")]
        public IActionResult GetBlogs()
        {
            var query = _dbContext.Blogs.AsNoTracking();
            var dt = GetDataTableFormDataFromRequest();

            string searchValue = dt.SearchValue;
            if (!string.IsNullOrEmpty(searchValue))
            {
                query = query.Where(m => 
                        m.Blog_Title.Contains(searchValue) ||
                        m.Blog_Author.Contains(searchValue) ||
                        m.Blog_Content.Contains(searchValue));
            }

            var model = query.Execute(dt);
            return Ok(model);
        }

        [ActionName("Create")]
        public IActionResult CreateBlog()
        {
            return View("CreateBlog");
        }

        [HttpPost]
        [ActionName("Save")]
        public async Task<IActionResult> SaveBlog(BlogDataModel blogDataModel)
        {
            await _dbContext.Blogs.AddAsync(blogDataModel);
            int result = await _dbContext.SaveChangesAsync();

            //return View("CreateBlog");
            return Redirect("/Blog/List");
        }

        [ActionName("Edit")]
        public async Task<IActionResult> EditBlog(string id)
        {
            bool isInt = int.TryParse(id, out int getById);
            var model = await _dbContext
               .Blogs
               .AsNoTracking()
               .FirstOrDefaultAsync(x => x.Blog_Id == getById);
            if (model == null)
                return Redirect("/Blog/List");

            return View("EditBlog", model);
        }

        [HttpPost]
        [ActionName("Update")]
        public async Task<IActionResult> UpdateBlog(string id, BlogDataModel blogDataModel)
        {
            bool isInt = int.TryParse(id, out int getById);
            if (blogDataModel == null || getById == 0)
                return Redirect("/Blog/List");

            var model = await _dbContext
                .Blogs
                .AsNoTracking()
                .FirstOrDefaultAsync(x => x.Blog_Id == getById);

            if (model == null)
                return Redirect("/Blog/List");

            model.Blog_Title = blogDataModel.Blog_Title;
            model.Blog_Author = blogDataModel.Blog_Author;
            model.Blog_Content = blogDataModel.Blog_Content;

            _dbContext.Blogs.Update(model);
            _dbContext.Entry(model).State = EntityState.Modified;
            int result = await _dbContext.SaveChangesAsync();
            return Redirect("/Blog/List");
        }

        public async Task<IActionResult> DeleteBlog(string id)
        {
            bool isInt = int.TryParse(id, out int getById);
            var model = await _dbContext
               .Blogs
               .AsNoTracking()
               .FirstOrDefaultAsync(x => x.Blog_Id == getById);
            if (model == null)
                return Redirect("/Blog/List");

            _dbContext.Blogs.Remove(model);
            _dbContext.Entry(model).State = EntityState.Deleted;
            int result = await _dbContext.SaveChangesAsync();
            return Redirect("/Blog/List");
        }

        [HttpPost]
        [ActionName("Delete")]
        public async Task<IActionResult> DeleteBlogById(string id)
        {
            bool isInt = int.TryParse(id, out int getById);
            var model = await _dbContext
               .Blogs
               .AsNoTracking()
               .FirstOrDefaultAsync(x => x.Blog_Id == getById);
            if (model == null)
                return Redirect("/Blog/List");

            _dbContext.Blogs.Remove(model);
            _dbContext.Entry(model).State = EntityState.Deleted;
            int result = await _dbContext.SaveChangesAsync();
            return Json(new { IsSuccess = result > 0 });
        }
    }
}

HPPMDotNetCore.MvcApp/Controllers/ChartController.cs
using HPPMDotNetCore.Models;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Runtime.InteropServices.WindowsRuntime;
using System.Security.Cryptography.Xml;

namespace HPPMDotNetCore.MvcApp.Controllers
{
    public class ChartController : Controller
    {
        public IActionResult PieChart()
        {
            PieChartResponseModel model = new PieChartResponseModel
            {
                Labels = new List<string> { "Team A", "Team B", "Team C", "Team D", "Team E" },
                Series = new List<int> { 44, 55, 13, 43, 22 }
            };
            return View(model);
        }

        public IActionResult LineChart()
        {
            var seryA = new SeryModel
            {
                Name = "Series A",
                Data = new List<double> { 1.4, 2, 2.5, 1.5, 2.5, 2.8, 3.8, 4.6 }
            };
            var seryB = new SeryModel
            {
                Name = "Series B",
                Data = new List<double> { 20, 29, 37, 36, 44, 45, 50, 58 }
            };

            LineChartResponseModel model = new LineChartResponseModel
            {
                Series = new List<SeryModel> { seryA, seryB },
                Categories = new List<string> { "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016" }
            };

            return View(model);
        }

        public IActionResult AreaChart()
        {

            SeryModel sery1 = new SeryModel
            {
                Name = "Series 1",
                Data = new List<double> { 45, 52, 38, 45, 19, 23, 2 }
            };
            AreaChartResponseModel model = new AreaChartResponseModel
            {
                Series = new List<SeryModel> { sery1 },
                Categories = new List<string> { "01 Jan", "02 Jan", "03 Jan", "04 Jan", "05 Jan", "06 Jan", "07 Jan" }
            };
            return View(model);
        }

        public IActionResult ColumnChart()
        {
            SeryModel sery1 = new SeryModel
            {
                Name = "Net Profit",
                Data = new List<double> { 44, 55, 57, 56, 61, 58, 63, 60, 66 }
            };

            SeryModel sery2 = new SeryModel
            {
                Name = "Revenue",
                Data = new List<double> { 76, 85, 101, 98, 87, 105, 91, 114, 94 }
            };

            SeryModel sery3 = new SeryModel
            {
                Name = "Free Cash Flow",
                Data = new List<double> { 35, 41, 36, 26, 45, 48, 52, 53, 41 }
            };

            ColumnChartResponseModel response = new ColumnChartResponseModel
            {
                Series = new List<SeryModel> { sery1, sery2, sery3 },
                Categories = new List<string> { "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct" }
            };
            return View(response);
        }

        public IActionResult BarChart()
        {
            BarSeryModel sery1 = new BarSeryModel
            {
                Data = new List<int> { 44, 55, 41, 64, 22, 43, 21 }
            };
            BarSeryModel sery2 = new BarSeryModel
            {
                Data = new List<int> { 53, 32, 33, 52, 13, 44, 32 }
            };

            BarChartResponseModel response = new BarChartResponseModel
            {
                Series = new List<BarSeryModel> { sery1, sery2 },
                Categories = new List<string> { "2001", " 2002", " 2003", " 2004", " 2005", " 2006", " 2007" }
            };

            return View(response);
        }

        public IActionResult BoxPlotChart()
        {
            return View();
        }
    }
}

HPPMDotNetCore.MvcApp/Controllers/PieChartController.cs
using HPPMDotNetCore.DbService;
using HPPMDotNetCore.Models;
using HPPMDotNetCore.MvcApp.Hubs;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.SignalR;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HPPMDotNetCore.MvcApp.Controllers
{
    public class PieChartController : Controller
    {
        private readonly EFDbContext _dbContext;
        private readonly IHubContext<ChatHub> _hubcontext;

        public PieChartController(EFDbContext dbContext, IHubContext<ChatHub> hubcontext)
        {
            _hubcontext = hubcontext;
            _dbContext = dbContext;
        }

        public async Task<IActionResult> Report()
        {
            var model = await GetPieChart();
            return View(model);
        }

        private async Task<PieChartResponseModel> GetPieChart()
        {
            var lst = await _dbContext.PieCharts.AsNoTracking().ToListAsync();
            var labels = lst.Select(x => x.PieChartLabel).ToList();
            var series = lst.Select(x => x.PieChartData).ToList();
            PieChartResponseModel model = new PieChartResponseModel
            {
                Labels = labels,
                Series = series
            };
            return model;
        }

        // public IActionResult Index()
        // {
        //     return View();
        // }

        public IActionResult CreatePieChart()
        {
            return View();
        }

        [HttpPost]
        [ActionName("Save")]
        public async Task<IActionResult> SavePieChart(PieChartDataModel pieChart)
        {
            await _dbContext.PieCharts.AddAsync(pieChart);
            int result = await _dbContext.SaveChangesAsync();

            var model = await GetPieChart();

            await _hubcontext.Clients.All.SendAsync("ReceiveChart", model.ToJson());
            return Json(pieChart);
        }
    }
}

HPPMDotNetCore.MvcApp/Controllers/ProductController.cs
using HPPMDotNetCore.DbService;
using HPPMDotNetCore.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Identity.Client;
using System.Collections.Generic;
using System.Linq.Dynamic.Core;
using System.Linq;
using System.Threading.Tasks;

namespace HPPMDotNetCore.MvcApp.Controllers
{
    public class ProductController : BaseController
    {

        private readonly EFDbContext _dbContext;

        public ProductController(EFDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        public IActionResult ProductIndex()
        {
            return View();
        }

        [ActionName("productList")]
        public IActionResult ProductList()
        {
            var query = _dbContext.Products.AsNoTracking();
            var dt = GetDataTableFormDataFromRequest();

            string searchValue = dt.SearchValue;
            if (!string.IsNullOrEmpty(searchValue))
            {
                query = query.Where(m =>
                        m.ProductCode.Contains(searchValue) ||
                        m.ProductName.Contains(searchValue) ||
                        m.ProductPrice.ToString().Contains(searchValue));
            }

            var model = query.Execute(dt);
            return Ok(model);
        }

        public IActionResult CreateProduct()
        {
            return View();
        }

        public async Task<IActionResult> Save(ProductDataModel model)
        {
            await _dbContext.Products.AddAsync(model);
            await _dbContext.SaveChangesAsync();
            
            return Json(model);
        }

        public async Task<ProductListResponseModel> GetProductList()
        {
            List<ProductDataModel> productList = await _dbContext
                           .Products.AsNoTracking().ToListAsync();
            ProductListResponseModel response = new ProductListResponseModel
            {
                ProductList = productList
            };
            return response;
        }
    }
}

HPPMDotNetCore.MvcApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HPPMDotNetCore.MvcApp</title>
   
    <partial name="_Styles"/>

    @RenderSection("css", required: false)

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">HPPMDotNetCore.MvcApp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Blog" asp-action="List">Blog-List</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="PieChart" asp-action="CreatePieChart">Create-Pie-Chart</a>
                        </li>
                        <li class="nav-item">
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
   <div class="page-wrapper chiller-theme toggled mb-5">
        <partial name="_MainNavigation" />
        <main role="main" class="pb-3 page-content">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - HPPMDotNetCore.MvcApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

   <partial name="_Scripts"/>
    @RenderSection("scripts", required: false)
   <script src="~/lib/signalr/dist/browser/signalr.js"></script>
    <script>
       
        getOrderCount();

        var connection = new signalR.HubConnectionBuilder().withUrl("/chatHub").build();

        connection.on("RecieveOrderCount", function (data) {
            var result = JSON.parse(data);
            showOrderCount(result.count);
            //bindPieChart(data.Series, data.Labels);
        });
        
        connection.start().then(function () {
            //document.getelementbyid("sendbutton").disabled = false;
        }).catch(function (err) {
            return console.error(err.tostring());
        });

        function getOrderCount(){
            $.ajax({
              type: "GET",
              url: "/ProductOrder/GetOrderCount",
              success: function(data){
                 showOrderCount(data);
              },
              error: function(){
                  alert("Error");
              }
            });
        }

        function showOrderCount(count){
            if(count > 0){
                 $('#orderCount').text(count);
                 $('#eCommerce').text(count);
            }else{
                $('#orderCount').text('');
                 $('#eCommerce').text('');
            }
        }
        
    </script>

</body>
</html>

HPPMDotNetCore.MvcApp/Views/Shared/_MainNavigation.cshtml
<a id="show-sidebar" class="btn btn-sm btn-dark" href="#">
    <i class="fas fa-bars"></i>
</a>
<nav id="sidebar" class="sidebar-wrapper">
    <div class="sidebar-content">
      <div class="sidebar-brand">
        <a href="#">pro sidebar</a>
        <div id="close-sidebar">
          <i class="fas fa-times"></i>
        </div>
      </div>
      <div class="sidebar-header">
        <div class="user-pic">
          <img class="img-responsive img-rounded" src="~/profile.jpg"
            alt="User picture">
        </div>
        <div class="user-info">
          <span class="user-name">Jhon
            <strong>Smith</strong>
          </span>
          <span class="user-role">Administrator</span>
          <span class="user-status">
            <i class="fa fa-circle"></i>
            <span>Online</span>
          </span>
        </div>
      </div>
      <!-- sidebar-header  -->
      <div class="sidebar-search">
        <div>
          <div class="input-group">
            <input type="text" class="form-control search-menu" placeholder="Search...">
            <div class="input-group-append">
              <span class="input-group-text">
                <i class="fa fa-search" aria-hidden="true"></i>
              </span>
            </div>
          </div>
        </div>
      </div>
      <!-- sidebar-search  -->
      <div class="sidebar-menu">
        <ul>
          <li class="header-menu">
            <span>General</span>
          </li>
          <li>
            <a href="#">
              <i class="fa fa-tachometer-alt"></i>
              <span>Dashboard</span>
              <span class="badge badge-pill badge-warning">New</span>
            </a>
          </li>
          <li class="sidebar-dropdown">
            <a href="#">
              <i class="fa fa-shopping-cart"></i>
              <span>E-commerce</span>
              <span class="badge badge-pill badge-danger" id="eCommerce"></span>
            </a>
            <div class="sidebar-submenu">
              <ul>
                <li>
                  <a asp-controller="Product" asp-action="ProductIndex">Products</a>
                </li>
                <li>
                  <a href="/ProductOrder/OrderIndex">
                      <span>Orders</span>
                      <span class="badge badge-pill badge-danger" id="orderCount">3</span>
                  </a>
                </li>
                <li>
                  <a href="#">Credit cart</a>
                </li>
              </ul>
            </div>
          </li>
          
          <li class="sidebar-dropdown">
            <a href="#">
              <i class="fa fa-chart-line"></i>
              <span>Charts</span>
            </a>
            <div class="sidebar-submenu">
              <ul>
                <li>
                   <a asp-area="" asp-controller="Chart" asp-action="PieChart">Pie Chart</a>
                </li>
                <li>
                 <a  asp-area="" asp-controller="Chart" asp-action="LineChart">Line Chart</a>
                </li>
                <li>
                    <a  asp-area="" asp-controller="Chart" asp-action="AreaChart">Area Chart</a>
                </li>
                 <li>
                    <a  asp-area="" asp-controller="Chart" asp-action="ColumnChart">Column Chart</a>
                </li>
                <li>
                    <a  asp-area="" asp-controller="Chart" asp-action="BarChart">Bar Chart</a>
                </li>
                 <li>
                    <a  asp-area="" asp-controller="Chart" asp-action="BoxPlotChart">Box-Plot Chart</a>
                </li>
              </ul>
            </div>
          </li>
          <li class="sidebar-dropdown">
            <a href="#">
              <i class="fa fa-globe"></i>
              <span>Maps</span>
            </a>
            <div class="sidebar-submenu">
              <ul>
                <li>
                  <a href="#">Google maps</a>
                </li>
                <li>
                  <a href="#">Open street map</a>
                </li>
              </ul>
            </div>
          </li>
          <li class="header-menu">
            <span>Extra</span>
          </li>
          <li>
            <a href="#">
              <i class="fa fa-book"></i>
              <span>Documentation</span>
              <span class="badge badge-pill badge-primary">Beta</span>
            </a>
          </li>
          <li>
            <a href="#">
              <i class="fa fa-calendar"></i>
              <span>Calendar</span>
            </a>
          </li>
          <li>
            <a href="#">
              <i class="fa fa-folder"></i>
              <span>Examples</span>
            </a>
          </li>
        </ul>
      </div>
      <!-- sidebar-menu  -->
    </div>
    <!-- sidebar-content  -->
    <div class="sidebar-footer">
      <a href="#">
        <i class="fa fa-bell"></i>
        <span class="badge badge-pill badge-warning notification">3</span>
      </a>
      <a href="#">
        <i class="fa fa-envelope"></i>
        <span class="badge badge-pill badge-success notification">7</span>
      </a>
      <a href="#">
        <i class="fa fa-cog"></i>
        <span class="badge-sonar"></span>
      </a>
      <a href="#">
        <i class="fa fa-power-off"></i>
      </a>
    </div>
  </nav>    

HPPMDotNetCore.MvcApp/Views/Shared/_Scripts.cshtml
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
@*<script src="https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.21/js/jquery.dataTables.min.js" integrity="sha512-BkpSL20WETFylMrcirBahHfSnY++H2O1W+UnEEO4yNIl+jI2+zowyoGJpbtk6bx97fBXf++WJHSSK2MV4ghPcg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>*@
<script src="https://cdnjs.cloudflare.com/ajax/libs/apexcharts/3.40.0/apexcharts.min.js" integrity="sha512-Kr1p/vGF2i84dZQTkoYZ2do8xHRaiqIa7ysnDugwoOcG0SbIx98erNekP/qms/hBDiBxj336//77d0dv53Jmew==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11.7.5/dist/sweetalert2.all.min.js" integrity="sha256-9AtIfusxXi0j4zXdSxRiZFn0g22OBdlTO4Bdsc2z/tY=" crossorigin="anonymous"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.2.7/pdfmake.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.2.7/vfs_fonts.js"></script>
<script src="https://cdn.datatables.net/v/bs5/jszip-2.5.0/dt-1.13.4/af-2.5.3/b-2.3.6/b-colvis-2.3.6/b-html5-2.3.6/b-print-2.3.6/cr-1.6.2/date-1.4.1/fc-4.2.2/fh-3.3.2/kt-2.9.0/r-2.4.1/rg-1.3.1/rr-1.3.3/sc-2.1.1/sb-1.4.2/sp-2.1.2/sl-1.6.2/sr-1.2.2/datatables.min.js"></script>

<script src="~/lib/signalr/dist/browser/signalr.js"></script>

<script src="~/js/sidebar.js"></script>

HPPMDotNetCore.MvcApp/Views/Shared/_Styles.cshtml
<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
<link rel="stylesheet" href="~/css/site.css" />
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous" />
@*<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.21/css/dataTables.bootstrap.min.css" integrity="sha512-BMbq2It2D3J17/C7aRklzOODG1IQ3+MHw3ifzBHMBwGO/0yUqYmsStgBjI0z5EYlaDEFnvYV7gNYdD3vFLRKsA==" crossorigin="anonymous" referrerpolicy="no-referrer" />*@
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/apexcharts/3.40.0/apexcharts.min.css" integrity="sha512-tJYqW5NWrT0JEkWYxrI4IK2jvT7PAiOwElIGTjALSyr8ZrilUQf+gjw2z6woWGSZqeXASyBXUr+WbtqiQgxUYg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/sweetalert2@11.7.5/dist/sweetalert2.min.css" integrity="sha256-aUL5sUzmON2yonFVjFCojGULVNIOaPxlH648oUtA/ng=" crossorigin="anonymous">

<link href="https://cdn.datatables.net/v/bs5/jszip-2.5.0/dt-1.13.4/af-2.5.3/b-2.3.6/b-colvis-2.3.6/b-html5-2.3.6/b-print-2.3.6/cr-1.6.2/date-1.4.1/fc-4.2.2/fh-3.3.2/kt-2.9.0/r-2.4.1/rg-1.3.1/rr-1.3.3/sc-2.1.1/sb-1.4.2/sp-2.1.2/sl-1.6.2/sr-1.2.2/datatables.min.css" rel="stylesheet"/>
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<link href="~/css/sidebar.css" rel="stylesheet" />